version: '3.8'

services:
  api:
    build:
      context: ./api
    ports:
      - "8080:8080"
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: mercedes
      POSTGRES_PASSWORD: mercedes
      POSTGRES_DB: infinity
    depends_on:
      - db
    networks:
      - mercedes_nw
  db:
    build:
      context: ./api/db/postgres
    environment:
      POSTGRES_USER: mercedes
      POSTGRES_PASSWORD: mercedes
      POSTGRES_DB: infinity
    ports:
      - "5432:5432"
    networks:
      - mercedes_nw
  webapp:
    build:
      context: ./webapp
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://api:8080/api
    depends_on:
      - api
    networks:
      - mercedes_nw

networks:
  mercedes_nw:
    driver: bridge
