version: '3.8'

services:
  webapp:
    build:
      context: ./webapp
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"
    depends_on:
      - api
  api:
    build:
      context: ./api
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    build:
      context: ./api/db/postgres
    environment:
      POSTGRES_USER: mercedes
      POSTGRES_PASSWORD: mercedes
      POSTGRES_DB: infinity
    ports:
      - "5432:5432"
